### ISSUE TITLE
NYC Open Data

### ISSUE THREAD

**Issue by epiquery** [presidential-innovation-fellows/open-opportunity-data#18]
Hello, 

The Measure of America team is excited to work on this challenge! Just wondering if the New York City Open Data leaders have been contacted to join the cities list? If not, we'd be happy to reach out on our end.

Thanks,
Rebecca 
Data Chief @ Measure of America

**Comment by rossdakin** [comment]
Hi Rebecca,

We're excited to have you!

Funny you should ask — we've been corresponding with NYC, but would love for you to reach out as well if you'd like to (pease CC Denice Ross: Denice_W_Ross@omb.eop.gov).

Thanks!
